### PR TITLE
Update spec.md

### PR DESCRIPTION
**Pull request by nionis**
more detailed description on how funding should behave

### CODE REVIEW

**Review by mathcrypto — APPROVED** [review]
Add these  cases:
 - If channel is `CLOSED`and `commitment`is **not set**, it should set it to `WAITING_FOR_COMMITMENT`
 - if channel is `WAITING_FOR_COMMITMENT` and `commitment` is **set**, it should set it to `OPEN`
 - if channel is `WAITING_FOR_COMMITMENT` and `commitment` is **not set**, it should set it to `CLOSE`

**Comment by nionis** [comment]
> if channel is `WAITING_FOR_COMMITMENT` and `commitment` is **not set**, it should set it to `CLOSE`

shouldn't it keep it to `WAITING_FOR_COMMITMENT` ?

**Comment by mathcrypto** [comment]
Well if it is kept to ```WAITING_FOR_COMMITMENT``` then A cannot close channel in case B does not set commitment and stake is blocked

**Review by mathcrypto — APPROVED** [review]

**Review by mathcrypto — APPROVED** [review]

**Comment by nionis** [comment]
yeah but in this section we only add scenarios when somebody is funding

**Comment by mathcrypto** [comment]
Ah ok then, those changes are correct

**Pull request merged**
